stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - data/raw/
    outs:
      - data/processed/

  train:
    cmd: python src/train.py
    deps:
      - data/processed/
    outs:
      - models/model.pkl